name: sdSkills
version: 1.0.0
api-version: 1.16
author: Michael Stolarz (stoladev)
main: me.stoladev.sdSkills.Main

description: A skilling plugin that tracks players' experiences, through multiple actions, throughout their gameplay.

permissions:
  sdSkills.skills:
    description: Grants the player access to the Skill Command feature.

commands:
  skills:
    description: Opens the Skills GUI.
    permission: sdSkills.skills
    usage: "Usage: /skills"

  chatcombat:
    description: Global chats your Combat Level.
    permission: sdSkills.skills
    usage: "Usage: /chat[skillname]"
  chatmining:
    description: Global chats your Mining Level.
    permission: sdSkills.skills
    usage: "Usage: /chat[skillname]"
  chatfarming:
    description: Global chats your Farming Level.
    permission: sdSkills.skills
    usage: "Usage: /chat[skillname]"
  chatagility:
    description: Global chats your Agility Level.
    permission: sdSkills.skills
    usage: "Usage: /chat[skillname]"
  chattotal:
    description: Global chats your Total Level.
    permission: sdSkills.skills
    usage: "Usage: /chat[skillname]"

  givecombat:
    description: Admin Command - Gives a player Combat XP.
    permission: sdSkills.admin
    usage: "Usage: /give[skillname] [player] [xptogive]"
  givemining:
    description: Admin Command - Gives a player Mining XP.
    permission: sdSkills.admin
    usage: "Usage: /give[skillname] [player] [xptogive]"
  givefarming:
    description: Admin Command - Gives a player Farming XP.
    permission: sdSkills.admin
    usage: "Usage: /give[skillname] [player] [xptogive]"
  giveagility:
    description: Admin Command - Gives a player Agility XP.
    permission: sdSkills.admin
    usage: "Usage: /give[skillname] [player] [xptogive]"

  setcombat:
    description: Admin Command - Sets a player's Combat Level.
    permission: sdSkills.admin
    usage: "Usage: /set[skillname] [player] [level]"
  setmining:
    description: Admin Command - Sets a player's Mining Level.
    permission: sdSkills.admin
    usage: "Usage: /set[skillname] [player] [level]"
  setfarming:
    description: Admin Command - Sets a player's Farming Level.
    permission: sdSkills.admin
    usage: "Usage: /set[skillname] [player] [level]"
  setagility:
    description: Admin Command - Sets a player's Agility Level.
    permission: sdSkills.admin
    usage: "Usage: /set[skillname] [player] [level]"
